name: Wudutale Release CD

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  export:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Export Linux
        uses: abarichello/godot-ci@3.6.2-stable
        with:
          args: >
            --headless
            --export-release "Linux"
            build/linux/wudutale.x86_64

      - name: Export Windows
        uses: abarichello/godot-ci@3.6.2-stable
        with:
          args: >
            --headless
            --export-release "Windows"
            build/windows/wudutale.exe

      - name: Zip Linux build
        run: |
          cd build/linux
          zip -r ../../wudutale-linux-x86_64.zip .

      - name: Zip Windows build
        run: |
          cd build/windows
          zip -r ../../wudutale-windows-x86_64.zip .

      - name: Upload Linux to Release
        uses: softprops/action-gh-release@v2
        with:
          files: wudutale-linux-x86_64.zip

      - name: Upload Windows to Release
        uses: softprops/action-gh-release@v2
        with:
          files: wudutale-windows-x86_64.zip